### ISSUE TITLE
Subscan page not updated for Aventus

### ISSUE THREAD

**Issue by dr-ngubo** [subscan-explorer/projects-info#66]
Hi, 

I noticed that the first character/letter of our company name (Aventus) is not in uppercase. I assumed it might be because the "project name" field in the PR [61](https://github.com/subscan-explorer/projects-info/pull/61) I submitted was in lowercase but after looking through some other PRs I noticed others too in lowercase but well represented on Subscan. However, I created a new PR [65](https://github.com/subscan-explorer/projects-info/pull/65) to update the "project name" field but it's still all lowercase on Subscan. 

Can you help, please?

**Comment by carlhong** [comment]
Thanks for feedback, it is updated.
