### ISSUE TITLE
Subscan page not updated for Riodefi

### ISSUE THREAD

**Issue by liuliang** [subscan-explorer/projects-info#67]
Hi,
Subscan page not updated for Riodefi

[ksm](https://kusama.subscan.io/parachain/2227)
[pr](https://github.com/subscan-explorer/projects-info/pull/64)

Can you help, please?

**Comment by carlhong** [comment]
Once new version is released (in one or two days), it will be updated.

**Comment by liuliang** [comment]
Thanks
